server.port: 8090


spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: root
    password: root
  main: allow-bean-definition-overriding=true

  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    change-log: classpath:/db/changelog/db.changelog-master.yaml